ServiceHost = "0.0.0.0"
ServicePort = 8000
Token = "123456789"

[minio]
Endpoint = "localhost:9000"
BucketName = "images"

[jwt]
Token = "peppa"
ExpiresIn = "720h"

[Redis]
DialTimeout = "10s"
ReadTimeout = "10s"
