// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/components": {
            "get": {
                "description": "Возвращает все доступные компоненты с опциональной фильтрацией по Названию",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Компоненты"
                ],
                "summary": "Получить все компоненты",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Название для фильтрации",
                        "name": "name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schemes.GetAllComponentsResponse"
                        }
                    }
                }
            }
        },
        "/api/components/": {
            "post": {
                "description": "Добавить новый компонент",
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "Компоненты"
                ],
                "summary": "Добавить компонент",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Изображение компонента",
                        "name": "image",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Название",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Всемирное наименование",
                        "name": "world_name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Количество",
                        "name": "amount",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Свойства",
                        "name": "properties",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/components/{component_id}": {
            "get": {
                "description": "Возвращает более подробную информацию об одном компоненте",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Компоненты"
                ],
                "summary": "Получить один компонент",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id компонента",
                        "name": "component_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ds.Component"
                        }
                    }
                }
            },
            "put": {
                "description": "Изменить данные полей о компоненте",
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "Компоненты"
                ],
                "summary": "Изменить компонент",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Идентификатор компонента",
                        "name": "component_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Название",
                        "name": "name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Всемирное наименование",
                        "name": "world_name",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Количество",
                        "name": "amount",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "Изображение компоненты",
                        "name": "image",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Свойства",
                        "name": "properties",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "delete": {
                "description": "Удаляет лекраство по id",
                "tags": [
                    "Компоненты"
                ],
                "summary": "Удалить компонент",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id компонента",
                        "name": "component_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/components/{component_id}/add_to_medicine": {
            "post": {
                "description": "Добавить выбранный компонент в черновик лекарства",
                "tags": [
                    "Компоненты"
                ],
                "summary": "Добавить в компонент",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id компонента",
                        "name": "component_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/medicines": {
            "get": {
                "description": "Возвращает все лекарства с фильтрацией по статусу и дате формирования",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Лекарства"
                ],
                "summary": "Получить все лекарства",
                "parameters": [
                    {
                        "type": "string",
                        "description": "статус лекарствоа",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "начальная дата формирования",
                        "name": "formation_date_start",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "конечная дата формирвания",
                        "name": "formation_date_end",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schemes.AllMedicinesResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Позволяет изменить название лекарства",
                "tags": [
                    "Лекарства"
                ],
                "summary": "Указать название лекарства",
                "parameters": [
                    {
                        "description": "Название лекарствоа",
                        "name": "name",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/app.SwaggerUpdateMedicineRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "delete": {
                "description": "Удаляет лекарство по id",
                "tags": [
                    "Лекарства"
                ],
                "summary": "Удалить лекарство",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/medicines/change_count/{component_id}": {
            "put": {
                "description": "Позволяет изменить вес компонента в лекарстве",
                "tags": [
                    "Лекарства"
                ],
                "summary": "Изменить вес компонента",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id компонента",
                        "name": "component_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Количество",
                        "name": "count",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schemes.ChangeCountReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/medicines/delete_component/{component_id}": {
            "delete": {
                "description": "Удалить компонент из лекарства",
                "tags": [
                    "Лекарства"
                ],
                "summary": "Удалить компонент из лекарства",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id компонента",
                        "name": "component_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/medicines/user_confirm": {
            "put": {
                "description": "Сформировать или удалить лекарство пользователем",
                "tags": [
                    "Лекарства"
                ],
                "summary": "Сформировать лекарство",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/medicines/{medicine_id}": {
            "get": {
                "description": "Возвращает подробную информацию о лекарстве и его названии",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Лекарства"
                ],
                "summary": "Получить одно лекарство",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id лекарствоа",
                        "name": "medicine_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schemes.MedicineResponse"
                        }
                    }
                }
            }
        },
        "/api/medicines/{medicine_id}/moderator_confirm": {
            "put": {
                "description": "Подтвердить или отменить лекарство модератором",
                "tags": [
                    "Лекарства"
                ],
                "summary": "Подтвердить лекарство",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id лекарства",
                        "name": "medicine_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "подтвердить",
                        "name": "confirm",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "boolean"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/user": {
            "get": {
                "description": "Получить информацию о профиле пользователя",
                "tags": [
                    "Пользователь"
                ],
                "summary": "Профиль",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "put": {
                "description": "Изменить все или часть данных профиля пользователя",
                "tags": [
                    "Пользователь"
                ],
                "summary": "Изменить профиль",
                "parameters": [
                    {
                        "description": "Новые значения",
                        "name": "new_fields",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schemes.ChangeUserReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/user/login": {
            "post": {
                "description": "Авторизует пользователя по логиню, паролю и отдаёт jwt токен для дальнейших запросов",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Пользователь"
                ],
                "summary": "Авторизация",
                "parameters": [
                    {
                        "description": "login and password",
                        "name": "user_credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schemes.LoginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schemes.AuthResp"
                        }
                    }
                }
            }
        },
        "/api/user/loguot": {
            "get": {
                "description": "Выход из аккаунта",
                "tags": [
                    "Пользователь"
                ],
                "summary": "Выйти из аккаунта",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/user/sign_up": {
            "post": {
                "description": "Регистрация нового пользователя",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Пользователь"
                ],
                "summary": "Регистрация",
                "parameters": [
                    {
                        "description": "login and password",
                        "name": "user_credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schemes.RegisterReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    },
    "definitions": {
        "app.SwaggerUpdateMedicineRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "ds.Component": {
            "type": "object",
            "required": [
                "amount",
                "name",
                "properties",
                "world_name"
            ],
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "image_url": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "properties": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                },
                "world_name": {
                    "type": "string"
                }
            }
        },
        "repository.ComponentWithCount": {
            "type": "object",
            "required": [
                "amount",
                "name",
                "properties",
                "world_name"
            ],
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "count": {
                    "type": "integer"
                },
                "image_url": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "properties": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                },
                "world_name": {
                    "type": "string"
                }
            }
        },
        "schemes.AllMedicinesResponse": {
            "type": "object",
            "properties": {
                "medicines": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/schemes.MedicineOutput"
                    }
                }
            }
        },
        "schemes.AuthResp": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "token_type": {
                    "type": "string"
                }
            }
        },
        "schemes.ChangeCountReq": {
            "type": "object",
            "required": [
                "count"
            ],
            "properties": {
                "count": {
                    "type": "integer"
                },
                "uri": {
                    "type": "object",
                    "required": [
                        "componentId"
                    ],
                    "properties": {
                        "componentId": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "schemes.ChangeUserReq": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "maxLength": 40
                },
                "name": {
                    "type": "string",
                    "maxLength": 60
                },
                "password": {
                    "type": "string",
                    "maxLength": 30
                }
            }
        },
        "schemes.GetAllComponentsResponse": {
            "type": "object",
            "properties": {
                "components": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ds.Component"
                    }
                },
                "draft_medicine": {
                    "type": "string"
                }
            }
        },
        "schemes.LoginReq": {
            "type": "object",
            "required": [
                "login",
                "password"
            ],
            "properties": {
                "login": {
                    "type": "string",
                    "maxLength": 30
                },
                "password": {
                    "type": "string",
                    "maxLength": 30
                }
            }
        },
        "schemes.MedicineOutput": {
            "type": "object",
            "properties": {
                "completion_date": {
                    "type": "string"
                },
                "creation_date": {
                    "type": "string"
                },
                "customer": {
                    "type": "string"
                },
                "formation_date": {
                    "type": "string"
                },
                "moderator": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                },
                "verification_status": {
                    "type": "string"
                }
            }
        },
        "schemes.MedicineResponse": {
            "type": "object",
            "properties": {
                "components": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/repository.ComponentWithCount"
                    }
                },
                "medicine": {
                    "$ref": "#/definitions/schemes.MedicineOutput"
                }
            }
        },
        "schemes.RegisterReq": {
            "type": "object",
            "required": [
                "login",
                "password"
            ],
            "properties": {
                "login": {
                    "type": "string",
                    "maxLength": 30
                },
                "password": {
                    "type": "string",
                    "maxLength": 30
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "127.0.0.1:8000",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Medicines",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
